import { DefaultTheme as RNNavigationTheme } from '@react-navigation/native';

import { Colors } from '../constants/colors';
import type { ThemeConstants } from '../types/Theme';

export const DefaultThemeConstants: ThemeConstants = {
  navBarHeight: 108,
  spacing: {
    'spacing-none': 0,
    'spacing-xxxs': 2,
    'spacing-xxs': 4,
    'spacing-xs': 8,
    'spacing-sm': 12,
    'spacing-md': 16,
    'spacing-lg': 20,
    'spacing-xl': 24,
    'spacing-xxl': 32,
    'spacing-xxxl': 40,
    'spacing-xxxxl': 48,
    'spacing-max': 96,
  },
  surfaceColor: {
    'surface-primary': Colors['colors-white'],
    'surface-secondary': Colors['colors-rose-50'],
    'surface-button': Colors['colors-lavender-100'],
    'surface-tertiary': Colors['colors-grey-100'],
    'surface-background': Colors['colors-lavender-50'],
    'surface-surface': Colors['colors-lavender-300'],
    'surface-disabled': Colors['colors-lavender-600'],
    'surface-invert': Colors['colors-lavender-500'],
    'surface-success': Colors['colors-green-50'],
    'surface-success-subtle': Colors['colors-green-25'],
    'surface-error': Colors['colors-red-50'],
    'surface-error-subtle': Colors['colors-red-25'],
    'surface-warning': Colors['colors-yellow-100'],
    'surface-warning-subtle': Colors['colors-yellow-25'],
    'surface-tertiary-subtle': Colors['colors-grey-25'],
    'surface-status-available': Colors['colors-green-50'],
    'surface-status-available-subtle': Colors['colors-green-25'],
    'surface-status-in-use': Colors['colors-rose-100'],
    'surface-status-in-use-subtle': Colors['colors-rose-50'],
    'surface-status-out-of-order': Colors['colors-grey-50'],
    'surface-status-out-of-order-subtle': Colors['colors-grey-25'],
    'surface-status-maintenance': Colors['colors-yellow-100'],
    'surface-status-maintenance-subtle': Colors['colors-yellow-25'],
    'surface-transparent': 'transparent',
    'surface-dark': Colors['colors-grey-900'],
  },
  shadowBox: {
    shadowColor: Colors['colors-black'],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  shadowCard: {
    shadowColor: Colors['colors-lavender-900'],
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  shadowFloating: {
    shadowColor: Colors['colors-lavender-900'],
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
  },
  shadowBottomNav: {
    shadowColor: Colors['colors-black'],
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  fontFamily: {
    poppins: 'Poppins',
  },
  borderWidth: {
    'border-width-none': 0,
    'border-width-xs': 1,
    'border-width-sm': 2,
    'border-width-md': 3,
    'border-width-lg': 4,
    'border-width-xl': 5,
    'border-width-xxl': 6,
    'border-width-xxxl': 8,
  },
  iconSize: {
    'icon-size-xs': 14,
    'icon-size-sm': 18,
    'icon-size-md': 20,
    'icon-size-lg': 22,
    'icon-size-xl': 24,
    'icon-size-xxl': 26,
    'icon-size-xxxl': 32,
    'icon-size-xxxxl': 48,
    'icon-size-xxxxxl': 64,
    'icon-size-xxxxxxl': 96,
    'icon-size-128': 128,
    'icon-size-160': 160,
    'icon-size-192': 192,
    'icon-size-256': 256,
  },
  cornerRad: {
    'corner-rad-none': 0,
    'corner-rad-sm': 4,
    'corner-rad-md': 8,
    'corner-rad-lg': 12,
    'corner-rad-xl': 16,
    'corner-rad-xxl': 24,
    'corner-rad-xxxl': 32,
    'corner-rad-full': 9999,
  },
  borderColor: {
    'border-primary': Colors['colors-grey-300'],
    'border-secondary': Colors['colors-grey-100'],
    'border-disabled': Colors['colors-grey-100'],
    'border-placeholder': Colors['colors-grey-400'],
    'border-invert': Colors['colors-white'],
    'border-error': Colors['colors-red-300'],
    'border-transparent': 'transparent',
  },
  fontSize: {
    'font-size-xs': 12,
    'font-size-sm': 14,
    'font-size-md': 16,
    'font-size-lg': 18,
    'font-size-xl': 20,
    'font-size-xxl': 24,
    'font-size-xxxl': 28,
    'font-size-xxxxl': 32,
  },
  fontWeight: {
    light: '300',
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  lineHeight: {
    'line-height-xs': 16,
    'line-height-sm': 18,
    'line-height-md': 20,
    'line-height-lg': 22,
    'line-height-xl': 24,
    'line-height-xxl': 28,
    'line-height-xxxl': 32,
  },
  fontColor: {
    'font-primary': Colors['colors-grey-900'],
    'font-secondary': Colors['colors-grey-300'],
    'font-highlight': Colors['colors-rose-500'],
    'font-light': Colors['colors-grey-400'],
    'font-disabled': Colors['colors-grey-400'],
    'font-placeholder': Colors['colors-grey-400'],
    'font-invert': Colors['colors-white'],
    'font-error': Colors['colors-red-600'],
    'font-success': Colors['colors-green-500'],
    'font-warning': Colors['colors-yellow-800'],
    'font-status-available': Colors['colors-green-700'],
    'font-status-in-use': Colors['colors-rose-500'],
    'font-status-out-of-order': Colors['colors-grey-300'],
    'font-status-maintenance': Colors['colors-yellow-800'],
  },
  letterSpacing: {
    label: 1.5,
  },
  componentSize: {
    fab: 56,
    iconContainer: 48,
    cardMaxWidth: 320,
    descriptionInput: 120,
    laundryImage: 112,
  },
  zIndex: {
    overlay: 9999,
    message: 10000,
    background: -9999,
    camera: -10000,
  },
  overlayColor: {
    modal: 'rgba(47,50,58,0.45)',
    dimmer: 'rgba(0,0,0,0.6)',
    backdrop: 'rgba(0,0,0,0.5)',
    glassButton: 'rgba(255,255,255,0.15)',
  },
  navigation: {
    ...RNNavigationTheme,
    colors: {
      ...RNNavigationTheme.colors,
      background: Colors['colors-white'],
    },
  },
};
