import { Colors } from './colors';
import type { BaseTheme } from './types';

export const darkTheme: BaseTheme = {
  spacing: {
    'spacing-none': 0,
    'spacing-xxxs': 2,
    'spacing-xxs': 4,
    'spacing-xs': 8,
    'spacing-sm': 12,
    'spacing-md': 16,
    'spacing-lg': 20,
    'spacing-xl': 24,
    'spacing-xxl': 32,
    'spacing-xxxl': 40,
    'spacing-xxxxl': 48,
    'spacing-max': 96,
  },
  surfaceColor: {
    'surface-primary': Colors['colors-grey-600'],
    'surface-secondary': Colors['colors-grey-700'],
    'surface-button': Colors['colors-lavender-700'],
    'surface-tertiary': Colors['colors-grey-500'],
    'surface-background': Colors['colors-grey-800'],
    'surface-surface': Colors['colors-grey-700'],
    'surface-disabled': Colors['colors-grey-500'],
    'surface-invert': Colors['colors-lavender-700'],
    'surface-success': Colors['colors-green-900'],
    'surface-success-subtle': Colors['colors-green-700'],
    'surface-error': Colors['colors-red-900'],
    'surface-error-subtle': Colors['colors-red-800'],
    'surface-warning': Colors['colors-yellow-900'],
    'surface-warning-subtle': Colors['colors-yellow-900'],
    'surface-tertiary-subtle': Colors['colors-grey-600'],
    'surface-status-available': Colors['colors-green-900'],
    'surface-status-available-subtle': Colors['colors-green-700'],
    'surface-status-in-use': Colors['colors-rose-900'],
    'surface-status-in-use-subtle': Colors['colors-rose-800'],
    'surface-status-out-of-order': Colors['colors-grey-500'],
    'surface-status-out-of-order-subtle': Colors['colors-grey-600'],
    'surface-status-maintenance': Colors['colors-yellow-900'],
    'surface-status-maintenance-subtle': Colors['colors-yellow-900'],
    'surface-transparent': 'transparent',
    'surface-dark': Colors['colors-grey-900'],
  },
  shadowBox: {
    shadowColor: Colors['colors-black'],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
    elevation: 8,
  },
  shadowCard: {
    shadowColor: Colors['colors-black'],
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 4,
  },
  shadowFloating: {
    shadowColor: Colors['colors-black'],
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.55,
    shadowRadius: 12,
    elevation: 8,
  },
  shadowBottomNav: {
    shadowColor: Colors['colors-black'],
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 4,
  },
  fontFamily: {
    poppins: 'Poppins',
  },
  borderColor: {
    'border-primary': Colors['colors-grey-400'],
    'border-secondary': Colors['colors-grey-500'],
    'border-disabled': Colors['colors-grey-600'],
    'border-placeholder': Colors['colors-grey-300'],
    'border-invert': Colors['colors-grey-200'],
    'border-error': Colors['colors-red-500'],
    'border-transparent': 'transparent',
  },
  fontSize: {
    'font-size-xs': 12,
    'font-size-sm': 14,
    'font-size-md': 16,
    'font-size-lg': 18,
    'font-size-xl': 20,
    'font-size-xxl': 24,
    'font-size-xxxl': 28,
    'font-size-xxxxl': 32,
  },
  fontWeight: {
    light: '300',
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
  },
  lineHeight: {
    'line-height-xs': 16,
    'line-height-sm': 18,
    'line-height-md': 20,
    'line-height-lg': 22,
    'line-height-xl': 24,
    'line-height-xxl': 28,
    'line-height-xxxl': 32,
  },
  fontColor: {
    'font-primary': Colors['colors-grey-25'],
    'font-secondary': Colors['colors-lavender-400'],
    'font-highlight': Colors['colors-rose-400'],
    'font-light': Colors['colors-grey-300'],
    'font-disabled': Colors['colors-grey-400'],
    'font-placeholder': Colors['colors-grey-300'],
    'font-invert': Colors['colors-grey-900'],
    'font-error': Colors['colors-red-500'],
    'font-success': Colors['colors-green-300'],
    'font-warning': Colors['colors-yellow-300'],
    'font-status-available': Colors['colors-green-300'],
    'font-status-in-use': Colors['colors-rose-400'],
    'font-status-out-of-order': Colors['colors-grey-300'],
    'font-status-maintenance': Colors['colors-yellow-300'],
  },
  cornerRad: {
    'corner-rad-none': 0,
    'corner-rad-sm': 4,
    'corner-rad-md': 8,
    'corner-rad-lg': 12,
    'corner-rad-xl': 16,
    'corner-rad-xxl': 24,
    'corner-rad-xxxl': 32,
    'corner-rad-full': 9999,
  },
  iconSize: {
    'icon-size-xs': 14,
    'icon-size-sm': 18,
    'icon-size-md': 20,
    'icon-size-lg': 22,
    'icon-size-xl': 24,
    'icon-size-xxl': 26,
    'icon-size-xxxl': 32,
    'icon-size-xxxxl': 48,
    'icon-size-xxxxxl': 64,
    'icon-size-xxxxxxl': 96,
    'icon-size-128': 128,
    'icon-size-160': 160,
    'icon-size-192': 192,
    'icon-size-256': 256,
  },
} satisfies BaseTheme;
